sudo: required
language: generic
dist: trusty

services:
 - docker
 
before_install:
 - sudo apt-get update
 - sudo apt-get install docker-ce

script:
 - docker build -t twitchax/termy:$TRAVIS_COMMIT .

after_success:
 - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER
 - docker push twitchax/termy:$TRAVIS_COMMIT
 - docker tag twitchax/termy:$TRAVIS_COMMIT twitchax/termy
 - docker push twitchax/termy