apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: termy
  name: termy
  namespace: termy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: termy
  template:
    metadata:
      labels:
        app: termy
    spec:
      containers:
      - image: twitchax/termy
        name: termy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: secrets
          readOnly: true
          mountPath: /etc/secrets
        securityContext:
          privileged: true
      volumes:
      - name: secrets
        secret:
          secretName: termy-secrets
