kind: Service
apiVersion: v1
metadata:
  name: termy-svc
  labels:
    app: termy
  namespace: {{namespace}}
spec:
  selector:
    app: termy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80